# Generated by Django 3.0.2 on 2020-01-23 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('position', models.CharField(choices=[('PG Senator', 'PG Senator'), ('UG Senator', 'UG Senator'), ('General Secretary Cultural', 'General Secretary Cultural'), ('General Secretary HAB', 'General Secretary HAB'), ('General Secretary Sports', 'General Secretary Sports'), ('General Secretary Technical', 'General Secretary Technical'), ('General Secretary Welfare', 'General Secretary Welfare'), ('Vice President', 'Vice President')], default='Vice President', max_length=64)),
                ('videos', models.FileField(upload_to='')),
                ('agenda', models.FileField(upload_to='')),
                ('key_points', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('total_residents', models.IntegerField(default=0)),
                ('no_of_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Junta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('role', models.CharField(choices=[('Voter', 'Voter'), ('Candidate', 'Candidate'), ('Election Commission', 'Election Commission')], default='Voter', max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1024)),
                ('answer', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_submitted', to='portal.Junta')),
                ('asked_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_asked', to='portal.Candidate')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='portal.Junta'),
        ),
    ]
