# Generated by Django 3.0.2 on 2020-01-31 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_auto_20200131_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='junta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='answered_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
