# Generated by Django 3.0.2 on 2020-01-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200131_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='asked_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
