# Generated by Django 3.0.2 on 2020-01-31 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200131_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['asked_on']},
        ),
    ]
